#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTMUX1,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTMUX2,         sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontLeftMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rearLeftMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rearRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     crankMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     slideMotor1,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     slideMotor2,   tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    frontRightServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rearRightServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    leftScoopServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    frontLeftServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rearLeftServo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    rightScoopServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    rightRadarServo,      tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    leftRadarServo,       tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo15,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_4,    servo16,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo17,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo18,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define armTouch                msensor_S3_1
#define slideTouch              msensor_S3_2
#define radarSonar              msensor_S3_3
#define gyroSensor              msensor_S3_4
#define leftIR                  msensor_S4_1
#define rightIR                 msensor_S4_2
#define sonarSensor             msensor_S4_3
#define colorSensor             msensor_S4_4

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="Auto.c" />
///
/// <summary>
///     This module is a template file and should not be modified except for
///     the above motor and sensor definitions. Code common to both Autonmous
///     and TeleOp modes should live in CommonCode.h. Code specific to only
///     Autonmous mode should live in AutoCode.h.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"

#define _AUTO_ONLY

#include "CommonCode.h"
#include "AutoCode.h"

/**
 *  This function is called to initialize the robot. It does initializations
 *  common to both Autonomous and TeleOp modes as well as initializations
 *  specific only to Autonomous mode.
 */
void RobotInit()
{
    CommonInit();
    AutoInit();
}   //RobotInit

/**
 *  This function is called before Autonomous mode starts.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void StartMode(int pgmMode)
{
    AutoStart();
}   //StartMode

/**
 *  This function is called after Autonomous mode ends.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void StopMode(int pgmMode)
{
    AutoStop();
}   //StopMode

/**
 *  This function is called to perform high frequency tasks that are common to
 *  both Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void HiFreqTasks(int pgmMode)
{
    CommonHiFreqTasks();
    AutoHiFreqTasks();
}   //HiFreqTasks

/**
 *  This function is called to perform input tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void InputTasks(int pgmMode)
{
    CommonInputTasks();
    AutoInputTasks();
}   //InputTasks

/**
 *  This function is called to perform the main competition tasks.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 *  @param time Specifies the running time since the mode started.
 */
void MainTasks(int pgmMode, float time)
{
    AutoTasks(time);
}   //MainTasks

/**
 *  This function is called to perform output tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to Autonomous
 *  mode.
 *
 *  @param pgmMode Specifies the program mode (Autonomous in this case).
 */
void OutputTasks(int pgmMode)
{
    AutoOutputTasks();
    CommonOutputTasks();
}   //OutputTasks

#include "..\ftclib\FtcAuto.h"
