#pragma config(Sensor, S1,     colorSensor,    sensorNone)
#pragma config(Motor,  motorA,          rollerMotor,   tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true)
    {
        if (nNxtButtonPressed == 1)
        {
            motor[rollerMotor] = -100;
        }
        else if (nNxtButtonPressed == 2)
        {
            motor[rollerMotor] = 100;
        }
        else
        {
            motor[rollerMotor] = 0;
        }
        wait1Msec(100);
    }
}
