#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    testServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define POS_INC                 1

task main()
{
    int pos = 0;

    servo[testServo] = 0;
    wait1Msec(1000);

    while (true)
    {
        nxtDisplayCenteredBigTextLine(3, "%d", pos);
        servo[testServo] = pos;
        if (nNxtButtonPressed == kLeftButton)
        {
            pos -= POS_INC;
            if (pos < 0)
            {
                pos = 0;
            }
        }
        else if (nNxtButtonPressed == kRightButton)
        {
            pos += POS_INC;
            if (pos > 255)
            {
                pos = 255;
            }
        }
        wait1Msec(100);
    }
}
