#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     frontLeftMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rearLeftMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     rearRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     slideMotor1,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     slideMotor2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     crankMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    frontRightServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rearRightServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    craneServo,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    frontLeftServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    rearLeftServo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void WaitForButton(TButtons button)
{
    while (nNxtButtonPressed != button)
    {
        wait1Msec(100);
    }

    while (nNxtButtonPressed == button)
    {
        wait1Msec(100);
    }
}

task main()
{
    servo[servo6] = 0;
    wait1Msec(1000);
    nMotorEncoder[motorA] = 0;
    clearDebugStream();

    for (int pos = 0; pos < 256; pos++)
    {
        nxtDisplayCenteredBigTextLine(3, "%3d", pos);
        servo[servo6] = pos;
        wait1Msec(50);
        writeDebugStream("%3d %3d\n", pos, nMotorEncoder[motorA]);
    }
    servo[servo6] = 0;
    wait1Msec(500);
}
