#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     testMotor1,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     testMotor2,    tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    nMotorEncoder[testMotor1] = 0;
    nMotorEncoder[testMotor2] = 0;
    while (true)
    {
        motor[testMotor1] = 30;
        motor[testMotor2] = 0;
        nxtDisplayCenteredBigTextLine(1, "%d", nMotorEncoder[testMotor1]);
        nxtDisplayCenteredBigTextLine(4, "%d", nMotorEncoder[testMotor2]);
        wait1Msec(100);
    }
}
